// Generated by extension/scripts/publish-growdesk.mjs - do not edit by hand.

/** The GrowDesk Capture Chrome extension GrowDesk currently offers. */
export const CAPTURE_EXTENSION = {
  id: "mnhjjndckpjiglmdlpelboiebdjcfaid",
  version: "1.0.3",
  download: "/downloads/growdesk-capture.zip",
  crx: "/capture/growdesk-capture.crx",
  updateManifest: "/capture/update.xml",
  /** Where this build looks for updates (set at build time). */
  builtUpdateUrl: "http://localhost:8787/update.xml",
} as const;
